name: CI

on:
  push:
    branches: [ main ]
  pull_request: ~

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pack and test
      run: ./build.ps1

    - name: Upload bin artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Bin
        path: artifacts/Bin

    - name: Upload logs artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: artifacts/Logs
