<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <Product>TFVC Migrator</Product>
    <Authors>Joseph N. Musser II</Authors>
    <Copyright>Copyright © 2020–2026 Joseph N. Musser II</Copyright>
    <AssemblyTitle>TFVC Migrator</AssemblyTitle>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RollForward>Major</RollForward>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="19.225.2" />
    <!-- Microsoft.TeamFoundationServer.Client pulls in a vulnerable version -->
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
    <PackageReference Include="TaskTupleAwaiter" Version="2.3.0" />
  </ItemGroup>

</Project>
